version: '3'
services: 
  client: 
    build: 
      dockerfile: packages/client/Dockerfile
      context: ./
    image: sevenapps/client:latest
    ports: 
      - "3000:3000"
    environment: 
      NODE_ENV: production